EmployeeManagment/Controllers/CenterController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;
using Services.Repository;

namespace EmployeeManagment.Controllers
{
    public class CenterController : Controller
    {
        private readonly ICenterRepository centerRepository;

        public CenterController(ICenterRepository centerRepository)
        {
            this.centerRepository = centerRepository;
        }
        [HttpPost]
        public IActionResult GetCenters([FromBody] int cityid)
        {
            var centers = centerRepository.Find(x => x.CityId == cityid);
            return Ok(centers);
        }

    }
}

EmployeeManagment/Controllers/EmployeeController.cs
using Domain.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using Services.Interfaces;
using Services.UniteOfWork;
using System.Runtime.Intrinsics.X86;

namespace EmployeeManagment.Controllers
{
    [Authorize(Policy = "onlysee")]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepository employeeRepository;
        private readonly IGovernorateRepository governorateRepository;
        private readonly ICityRepository cityRepository;
        private readonly IToastNotification toastNotification;

        public EmployeeController(IEmployeeRepository employeeRepository, IGovernorateRepository governorateRepository, ICityRepository cityRepository, IToastNotification toastNotification)
        {
            this.employeeRepository = employeeRepository;
            this.governorateRepository = governorateRepository;
            this.cityRepository = cityRepository;
            this.toastNotification = toastNotification;
            
        }

        [HttpGet]
        [Authorize(Policy = "crud")]
        public async Task<IActionResult> AddEmployee()
        {
            ViewBag.Governate = await governorateRepository.GetAll();
            return View();
        }

        [HttpPost]
        [Authorize(Policy = "crud")]
        public async Task<IActionResult> AddEmployee(Employee employee)
        {
            if(ModelState.IsValid)
            {
                if(employee.Id==0)
                {
                    await employeeRepository.Insert(employee);
                   
                }
                else
                {
                    await employeeRepository.Update(employee);
                }
                if (await employeeRepository.Save() == 0)
                {
                    toastNotification.AddSuccessToastMessage("Saved Successfully");
                    return RedirectToAction("GetAllEmployee");
                }
            }
            ViewBag.Governate = await employeeRepository.GetAll();
            return View(employee);
        }
        [HttpGet]
        [Authorize(Policy = "onlysee")]
        public async Task< IActionResult> GetAllEmployee()
        {
         var Employess = await employeeRepository.GetAll(new[] { "Governorate","City", "center" });
          return View(Employess);
        }
        [HttpPost]
        public JsonResult SSNIsAlreadyExist(string SSN,int Id=0)
        {
            var employessn = employeeRepository.Find(x => x.SSN == SSN).FirstOrDefault();
            if (employessn != null)
            {
                if(Id == 0)
                {
                    return Json(false);
                }
                if (Id == employessn.Id)
                {
                    return Json(true);
                }
            }
           return Json(true);
        }

        [HttpPost]
        [Authorize(Policy = "crud")]
        public async Task< IActionResult> DeleteEmployee(int id)
        {
            var employee= await employeeRepository.Get(id);
            if (employee == null)
            {
                return BadRequest();
            }
           await employeeRepository.Remove(employee);
           return Ok();
        }

        [HttpGet]
        [Authorize(Policy = "crud")]
        public async Task< IActionResult> UpdateEmployee(int id)
        {
            ViewBag.Governate = await governorateRepository.GetAll();
            var employe = employeeRepository.findbyId(x => x.Id == id, new[]{"Governorate", "City", "center" });
            return View("AddEmployee",employe);
        }

        [HttpGet]
        public IActionResult AssessDenied()
        {
            return View();
        }

      
    }
 
  
}

EmployeeManagment/Controllers/ReportController.cs
using AspNetCore.Reporting;
using Domain.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManagment.Controllers
{
    public class ReportController : Controller
    {
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly EmployeeDbContext employeeDbContext;

        public ReportController(IWebHostEnvironment webHostEnvironment, EmployeeDbContext employeeDbContext)
        {
            this.webHostEnvironment = webHostEnvironment;
            this.employeeDbContext = employeeDbContext;
        }
        public IActionResult Index()
        {
           
            return View();
        }
        public FileContentResult DownloadReport()
        {
            string format = "PDF";
            string extinission = "pdf";
            string mimetype = "application/pdf";
            string reportpath = $"{webHostEnvironment.WebRootPath}\\Reports\\Report1.rdlc";
            var data = employeeDbContext.GetAllEmployee();
            var datatable = HelperClass.ToDataTable(data);
            var localreport = new LocalReport(reportpath);
            localreport.AddDataSource("DataSet1", datatable);
            var result = localreport.Execute(RenderType.Pdf, 1, null, mimetype);
            return File(result.MainStream, mimetype);
        }
    }
}

EmployeeManagment/Views/Employee/AddEmployee.cshtml
@model Employee

@{
    ViewData["Title"] = "Create";
}


<div class="row">

        <form  asp-action="AddEmployee" class="col-md-12 row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @if (Model != null)
        {
            <input type="hidden" asp-for="Id" />
        }
               
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Name" class="control-label mb-1 fw-bold text-pr"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        <div class="form-group col-md-6 mb-3">
            <label asp-for="Salary" class="control-label mb-1 fw-bold"></label>
                <input asp-for="Salary" class="form-control" type="text" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
        <div class="form-group col-md-6 mb-3">
            <label asp-for="Age" class="control-label mb-1 fw-bold"></label>
                <input asp-for="Age" class="form-control" type="text" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>

        <div class="form-group col-md-6 mb-3">
            <label asp-for="SSN" class="control-label mb-1 fw-bold"></label>
                <input asp-for="SSN" class="form-control" type="text" />
                <span asp-validation-for="SSN" class="text-danger"></span>
            </div>

        <div class="form-group col-md-6 mb-3">
            <label asp-for="Gender" class="control-label mb-1 fw-bold">Gender</label>
            <select asp-for="Gender" class="form-select">
                <option selected disabled>Selecte Gender</option>
                <option>Male</option>
                <option>Female</option>
            </select>
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
        
    
        <div class="form-group col-md-6 mb-3">
            <label asp-for="State" class="control-label mb-1 fw-bold">State</label>
            <select asp-for="State" class="form-select mb-1">
                <option selected disabled>Select Marital Status</option>
                <option >Married</option>
                <option>Unmarried</option>
                <option >Engaged</option>
            </select>
            <span asp-validation-for="State" class="text-danger"></span>
        </div>
    

        <div class="form-group col-md-6 mb-3">
            <label asp-for="GovernorateId" class="control-label mb-1 fw-bold">Governorate</label>
            <select asp-for="GovernorateId" class="form-select" id="governate">
                <option selected disabled>Select Governate</option>
                @foreach (var item in ViewBag.Governate)
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
            <span asp-validation-for="GovernorateId" class="text-danger"></span>
        </div>
   
        

        <div class="form-group col-md-6 mb-3">
            <label asp-for="CityId" class="control-label mb-1 fw-bold">City</label>
            <select asp-for="CityId" class="form-select" id="PickUpCity">
                <option selected>Selecte City</option>
                @if (Model != null)
                {
                    <option value="@Model.City.Id">@Model.City.Name</option>
                }
               
            </select>
            <span asp-validation-for="CityId" class="text-danger"></span>
        </div>

        <div class="form-group col-md-6 mb-3">
            <label asp-for="centerId" class="control-label mb-1 fw-bold">Center</label>
            <select asp-for="centerId" class="form-select" id="PickUpCenter">
                <option selected>Selecte Center</option>
                @if (Model != null)
                {
                    <option value="@Model.center.Id">@Model.center.Name</option>

                }
            </select>
            <span asp-validation-for="centerId" class="text-danger"></span>
        </div>

        


            <div class="form-group col-md-12 text-end">
                <input type="submit" value="Save User Details" class="btn btn-primary" />
            </div>
            
        </form>

</div>
@section Scripts{
    <script type="text/javascript">

        $(document).ready(function () {
            $('#governate').on('change', function () {
               
                var City = $("#PickUpCity");
                var center = $("#PickUpCenter");

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("GetCities","City")",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify($(this).val()),
                    success: function (data) {
                        debugger;
                        City.empty();
                        center.empty().append($('<option>', {
                            value: '',
                            text: 'Select Center'
                        }));
                        City.append($('<option>', {
                            value: '',
                            text: 'Select City'
                        }));
                        $.each(data, function (index, city) {
                            City.append("<option value='" + city.id + "'>" + city.name + "</option>");
                        });
          

                    }
                 
                });


            });


            $('#PickUpCity').on('change', function () {

                var center = $("#PickUpCenter");
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("GetCenters","Center")",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify($(this).val()),
                    success: function (data) {
                        debugger;
                        center.empty();
                        $.each(data, function (index, centers) {
                            center.append("<option value='" + centers.id + "'>" + centers.name + "</option>");
                        });


                    }

                });


            });

        });

    </script>


}

EmployeeManagment/Views/Employee/AssessDenied.cshtml
@{
    Layout=null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Access Denied</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="UTF-8">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <style>
        body {
            background-color: black;
            color: white;
        }

        h1 {
            color: red;
        }

        h6 {
            color: red;
            text-decoration: underline;
        }

    </style>
</head>
<body>
    <div class="w3-display-middle">
        <h1 class="w3-jumbo w3-animate-top w3-center"><code>Access Denied</code></h1>
        <hr class="w3-border-white w3-animate-left" style="margin:auto;width:50%">
        <h3 class="w3-center w3-animate-right">You dont have permission to view this site.</h3>
        <h3 class="w3-center w3-animate-zoom">🚫🚫🚫🚫</h3>
        <h6 class="w3-center w3-animate-zoom">error code:403 forbidden</h6>
    </div>
</body>
</html>

EmployeeManagment/Views/Employee/GetAllEmployee.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> usermanager
@inject SignInManager<ApplicationUser> signmanager
@model List<Employee>

<div class="d-flex justify-content-between align-items-center mb-3">

    @if (signmanager.IsSignedIn(User) && User.IsInRole("admin"))
    {

        <div class="d-flex justify-content-end align-items-center mb-3">
            <a asp-action="AddEmployee" class="d-block btn btn-success" asp-controller="Employee">
                <i class="fa-solid fa-user-plus"></i>
            </a>
        </div>

    }

    <a asp-action="DownloadReport" class="d-block btn btn-success" asp-controller="Report">
        <i class="fa-solid fa-print"></i>
    </a>

    
</div>



<div class="table-responsive">
    <table id="myTable" class="table table-hover ">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Salary</th>
                <th scope="col">Age</th>
                <th scope="col">SSN</th>
                <th scope="col">Status</th>
                <th scope="col">Governate</th>
                <th scope="col">City</th>
                <th scope="col">Center</th>
                @if (signmanager.IsSignedIn(User) && User.IsInRole("admin"))
                {

                    <th scope="col"></th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr id="@item.Id">
                    <td>@item.Name</td>
                    <td>@item.Salary</td>
                    <td>@item.Age</td>
                    <td>@item.SSN</td>
                    <td>@item.State</td>
                    <td>@item.Governorate.Name</td>
                    <td>@item.City.Name</td>
                    <td>@item.center.Name</td>
                    @if (signmanager.IsSignedIn(User) && User.IsInRole("admin"))
                    {

                        <td class="d-flex justify-content-between align-items-center">

                            <a asp-action="UpdateEmployee" asp-route-id="@item.Id" asp-controller="Employee">
                                <button class="btn btn-warning" type="button">
                                    <i class="fa-solid fa-pen"></i>
                                </button>
                            </a>

                            <button class="btn btn-danger" value="@item.Id" onclick="Delete(@item.Id)">
                                <i class="fa-solid fa-delete-left"></i>
                            </button>

                        </td>

                    }

                </tr>
            }

        </tbody>
    </table>

</div>

@section Scripts{
    <script type="text/javascript">

        function Delete(id){
            debugger
            Swal.fire({
                title: 'Do you want to Delete ?',
                showDenyButton: true,
                showCancelButton: false,
                confirmButtonText: 'Delete',
                denyButtonText: `Don't Delete`,
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("DeleteEmployee", "Employee")',
                        data: {id:id},
                        success: function () {
                            document.getElementById(id).style.display="none";
                        },
                        error: function () {
                            alert("Error while deleting data");
                        }
                    });
                    Swal.fire('Deleted!', '', 'success')
                } else if (result.isDenied) {
                    Swal.fire('not deleted', '', 'info')
                }
            });
        }
        $(document).ready(function(){
          
            $('#myTable').dataTable();

        });

        
      
    </script>

}